name: Update API Types

on:
  push:
    branches:
      - main
    paths:
      - "openapi.yml"

jobs:
  update-api-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v2

      - name: Install Project Dependencies
        run: bun i

      - name: Update API types
        run: bun run update-api-types

      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if git diff --quiet; then
            echo "No changes after generating types."
            exit 0
          fi

          BRANCH_NAME="chore/update-api-types-$(date +'%Y%m%d%H%M%S')"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          git add lib/schema.d.ts
          git commit -m "chore: update API types"
          git push origin $BRANCH_NAME

          gh pr create \
            --head "$BRANCH_NAME" \
            --base main \
            --title "chore: update API types" \
            --body "This PR updates API types from latest openapi.yml."
